const uint BM = 64u, BN = 128u, BK = 16u;
const uint AS = BK + 4u;
const uint BS = BN + 4u;
uint K = (uint)in0_shape[1];
uint N = (uint)in1_shape[1];
uint lid = thread_position_in_threadgroup.x;
uint sg = lid / 32u;
uint sgm = sg / 4u;
uint sgn = sg % 4u;
uint m0 = threadgroup_position_in_grid.y * BM;
uint n0 = threadgroup_position_in_grid.x * BN;
threadgroup float As[64u * 20u];
threadgroup float Bs[16u * 132u];
simdgroup_float8x8 c00(0.0f), c01(0.0f), c02(0.0f), c03(0.0f);
simdgroup_float8x8 c10(0.0f), c11(0.0f), c12(0.0f), c13(0.0f);
simdgroup_float8x8 c20(0.0f), c21(0.0f), c22(0.0f), c23(0.0f);
simdgroup_float8x8 c30(0.0f), c31(0.0f), c32(0.0f), c33(0.0f);
uint ar = lid / 4u; uint ac = (lid % 4u) * 4u;
uint br0 = lid / 32u; uint bc = (lid % 32u) * 4u;
uint br1 = br0 + 8u;
const device float* Ag = in0 + (m0 + ar) * K + ac;
const device float* Bg0 = in1 + br0 * N + n0 + bc;
const device float* Bg1 = in1 + br1 * N + n0 + bc;
threadgroup float* Asub = As + (sgm * 32u) * AS;
threadgroup float* Bsub = Bs + sgn * 32u;
for (uint k0 = 0; k0 < K; k0 += BK) {
    float4 av = *((const device float4*)(Ag + k0));
    float4 bv0 = *((const device float4*)(Bg0 + k0 * N));
    float4 bv1 = *((const device float4*)(Bg1 + k0 * N));
    threadgroup_barrier(mem_flags::mem_threadgroup);
    *((threadgroup float4*)(As + ar * AS + ac)) = av;
    *((threadgroup float4*)(Bs + br0 * BS + bc)) = bv0;
    *((threadgroup float4*)(Bs + br1 * BS + bc)) = bv1;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint kk = 0; kk < BK; kk += 8u) {
        simdgroup_float8x8 a0, a1, a2, a3, b0, b1, b2, b3;
        simdgroup_load(a0, Asub + 0u * AS + kk, (ulong)AS);
        simdgroup_load(a1, Asub + 8u * AS + kk, (ulong)AS);
        simdgroup_load(a2, Asub + 16u * AS + kk, (ulong)AS);
        simdgroup_load(a3, Asub + 24u * AS + kk, (ulong)AS);
        simdgroup_load(b0, Bsub + kk * BS + 0u, (ulong)BS);
        simdgroup_load(b1, Bsub + kk * BS + 8u, (ulong)BS);
        simdgroup_load(b2, Bsub + kk * BS + 16u, (ulong)BS);
        simdgroup_load(b3, Bsub + kk * BS + 24u, (ulong)BS);
        simdgroup_multiply_accumulate(c00, a0, b0, c00);
        simdgroup_multiply_accumulate(c01, a0, b1, c01);
        simdgroup_multiply_accumulate(c02, a0, b2, c02);
        simdgroup_multiply_accumulate(c03, a0, b3, c03);
        simdgroup_multiply_accumulate(c10, a1, b0, c10);
        simdgroup_multiply_accumulate(c11, a1, b1, c11);
        simdgroup_multiply_accumulate(c12, a1, b2, c12);
        simdgroup_multiply_accumulate(c13, a1, b3, c13);
        simdgroup_multiply_accumulate(c20, a2, b0, c20);
        simdgroup_multiply_accumulate(c21, a2, b1, c21);
        simdgroup_multiply_accumulate(c22, a2, b2, c22);
        simdgroup_multiply_accumulate(c23, a2, b3, c23);
        simdgroup_multiply_accumulate(c30, a3, b0, c30);
        simdgroup_multiply_accumulate(c31, a3, b1, c31);
        simdgroup_multiply_accumulate(c32, a3, b2, c32);
        simdgroup_multiply_accumulate(c33, a3, b3, c33);
    }
}
uint om = m0 + sgm * 32u;
uint on = n0 + sgn * 32u;
device float* O0 = out0 + (om + 0u) * N + on;
device float* O1 = out0 + (om + 8u) * N + on;
device float* O2 = out0 + (om + 16u) * N + on;
device float* O3 = out0 + (om + 24u) * N + on;
simdgroup_store(c00, O0 + 0u, (ulong)N); simdgroup_store(c01, O0 + 8u, (ulong)N); simdgroup_store(c02, O0 + 16u, (ulong)N); simdgroup_store(c03, O0 + 24u, (ulong)N);
simdgroup_store(c10, O1 + 0u, (ulong)N); simdgroup_store(c11, O1 + 8u, (ulong)N); simdgroup_store(c12, O1 + 16u, (ulong)N); simdgroup_store(c13, O1 + 24u, (ulong)N);
simdgroup_store(c20, O2 + 0u, (ulong)N); simdgroup_store(c21, O2 + 8u, (ulong)N); simdgroup_store(c22, O2 + 16u, (ulong)N); simdgroup_store(c23, O2 + 24u, (ulong)N);
simdgroup_store(c30, O3 + 0u, (ulong)N); simdgroup_store(c31, O3 + 8u, (ulong)N); simdgroup_store(c32, O3 + 16u, (ulong)N); simdgroup_store(c33, O3 + 24u, (ulong)N);
