"""Generated by autotuner bind. Replays recorded op streams with shipped cuts
replaced by kernel calls; do not edit."""

import mlx.core as mx
from autotuner_runtime import kernels as _kernels
from autotuner_runtime.captured_kernels import captured as _captured
from autotuner_runtime.swap import ReplayWrapper, flatten_arrays, resolve_value as _resolve_value
from autotuner_runtime.swap import state_signature as _state_signature


# serves model.model.layers.0, model.model.layers.1, model.model.layers.11, model.model.layers.13, model.model.layers.3, model.model.layers.4, model.model.layers.6, model.model.layers.7, model.model.layers.9
class W_rae66687cb9df03fe_predeq_sg2x4__r95aa6c37bb25ef99_prefill_bk64__r1f9367e50750eb01_unroll_hoist__r036a72bd97248ec8_s0tile_sgfullunroll(ReplayWrapper):
    KERNEL_IDS = ['rae66687cb9df03fe_predeq_sg2x4', 'r95aa6c37bb25ef99_prefill_bk64', 'r1f9367e50750eb01_unroll_hoist', 'r036a72bd97248ec8_s0tile_sgfullunroll']

    def __init__(self, wrapped, specs=None):
        super().__init__(wrapped, specs)
        object.__setattr__(self, '_weights', (
            _resolve_value(self.wrapped, 'operator_norm.weight'),
            _resolve_value(self.wrapped, 'conv.in_proj.weight'),
            _resolve_value(self.wrapped, 'conv.in_proj.scales'),
            _resolve_value(self.wrapped, 'conv.in_proj.biases'),
            _resolve_value(self.wrapped, 'conv.conv.weight'),
            _resolve_value(self.wrapped, 'conv.out_proj.weight'),
            _resolve_value(self.wrapped, 'conv.out_proj.scales'),
            _resolve_value(self.wrapped, 'conv.out_proj.biases'),
            _resolve_value(self.wrapped, 'ffn_norm.weight'),
            _resolve_value(self.wrapped, 'feed_forward.w1.weight'),
            _resolve_value(self.wrapped, 'feed_forward.w1.scales'),
            _resolve_value(self.wrapped, 'feed_forward.w1.biases'),
            _resolve_value(self.wrapped, 'feed_forward.w3.weight'),
            _resolve_value(self.wrapped, 'feed_forward.w3.scales'),
            _resolve_value(self.wrapped, 'feed_forward.w3.biases'),
            _resolve_value(self.wrapped, 'feed_forward.w2.weight'),
            _resolve_value(self.wrapped, 'feed_forward.w2.scales'),
            _resolve_value(self.wrapped, 'feed_forward.w2.biases'),
        ))

    def __call__(self, a0, a1, cache=None):
        _n = a0.shape[1] if isinstance(a0, mx.array) and a0.ndim > 1 else -1
        if not (2 <= _n <= 2048 and a0 is not None and a0.shape == (1, _n, 2048) and a0.dtype == mx.bfloat16 and a1 is None and _state_signature(cache) == ('ArraysCache', ('dict', (('cache', ('list', (None,))), ('left_padding', None), ('lengths', None))))):
            return self.wrapped(a0, a1, cache=cache)
        _w = self._weights
        v0 = a0
        v1 = _w[0]
        v2 = mx.fast.rms_norm(v0, v1, 1e-05)
        v3 = _w[1]
        v4 = _w[2]
        v5 = _w[3]
        _s = self._specs['rae66687cb9df03fe_predeq_sg2x4']
        _ins = [v2, v3, v4, v5]
        _outs = _kernels.try_sized(_s, _ins) if 948 <= _n <= 2048 else None
        if _outs is None:
            v6 = mx.quantized_matmul(v2, v3, scales=v4, biases=v5, transpose=True, group_size=64, bits=4, mode='affine')
            v7, v8, v9 = mx.split(v6, 3, axis=-1)
            v10 = (v7 * v9)
        else:
            v8 = _outs[0]
            v10 = _outs[1]
        cache.__getitem__(0)
        v11 = mx.zeros((1, 2, 2048), dtype=mx.bfloat16)
        v12 = mx.concatenate([v11, v10], axis=1)
        v13 = v12[(slice(None, None, None), slice(-2, None, None), slice(None, None, None))]
        cache.__setitem__(0, v13)
        v14 = _w[4]
        v15 = mx.conv1d(v12, v14, 1, 0, 1, 2048)
        v16 = (v8 * v15)
        v17 = _w[5]
        v18 = _w[6]
        v19 = _w[7]
        v20 = _w[8]
        _s = self._specs['r95aa6c37bb25ef99_prefill_bk64']
        _ins = [v16, v17, v18, v19, v0, v20]
        _outs = _kernels.try_sized(_s, _ins) if 439 <= _n <= 2048 else None
        if _outs is None:
            v21 = mx.quantized_matmul(v16, v17, scales=v18, biases=v19, transpose=True, group_size=64, bits=4, mode='affine')
            v22 = (v0 + v21)
            v23 = mx.fast.rms_norm(v22, v20, 1e-05)
        else:
            v22 = _outs[0]
            v23 = _outs[1]
        v24 = _w[9]
        v25 = _w[10]
        v26 = _w[11]
        v27 = _w[12]
        v28 = _w[13]
        v29 = _w[14]
        _s = self._specs['r1f9367e50750eb01_unroll_hoist']
        _ins = [v23, v24, v25, v26, v27, v28, v29]
        _outs = _kernels.try_sized(_s, _ins) if 948 <= _n <= 2048 else None
        if _outs is None:
            v30 = mx.quantized_matmul(v23, v24, scales=v25, biases=v26, transpose=True, group_size=64, bits=4, mode='affine')
            v31 = mx.quantized_matmul(v23, v27, scales=v28, biases=v29, transpose=True, group_size=64, bits=4, mode='affine')
        else:
            v30 = _outs[0]
            v31 = _outs[1]
        v32, = flatten_arrays(_kernels.imported('mlx_lm.models.activations.swiglu')(v30, v31))
        v33 = _w[15]
        v34 = _w[16]
        v35 = _w[17]
        _s = self._specs['r036a72bd97248ec8_s0tile_sgfullunroll']
        _ins = [v32, v33, v34, v35, v22]
        _outs = _kernels.try_sized(_s, _ins) if 948 <= _n <= 2048 else None
        if _outs is None:
            v36 = mx.quantized_matmul(v32, v33, scales=v34, biases=v35, transpose=True, group_size=64, bits=4, mode='affine')
            v37 = (v22 + v36)
        else:
            v37 = _outs[0]
        return v37


# serves model.model.layers.10, model.model.layers.12, model.model.layers.14, model.model.layers.2, model.model.layers.5, model.model.layers.8
class W_r95aa6c37bb25ef99_prefill_bk64__r1f9367e50750eb01_unroll_hoist__r036a72bd97248ec8_s0tile_sgfullunroll(ReplayWrapper):
    KERNEL_IDS = ['r95aa6c37bb25ef99_prefill_bk64', 'r1f9367e50750eb01_unroll_hoist', 'r036a72bd97248ec8_s0tile_sgfullunroll']

    def __init__(self, wrapped, specs=None):
        super().__init__(wrapped, specs)
        object.__setattr__(self, '_weights', (
            _resolve_value(self.wrapped, 'operator_norm.weight'),
            _resolve_value(self.wrapped, 'self_attn.q_proj.weight'),
            _resolve_value(self.wrapped, 'self_attn.q_proj.scales'),
            _resolve_value(self.wrapped, 'self_attn.q_proj.biases'),
            _resolve_value(self.wrapped, 'self_attn.k_proj.weight'),
            _resolve_value(self.wrapped, 'self_attn.k_proj.scales'),
            _resolve_value(self.wrapped, 'self_attn.k_proj.biases'),
            _resolve_value(self.wrapped, 'self_attn.v_proj.weight'),
            _resolve_value(self.wrapped, 'self_attn.v_proj.scales'),
            _resolve_value(self.wrapped, 'self_attn.v_proj.biases'),
            _resolve_value(self.wrapped, 'self_attn.q_layernorm.weight'),
            _resolve_value(self.wrapped, 'self_attn.k_layernorm.weight'),
            _resolve_value(self.wrapped, 'self_attn.out_proj.weight'),
            _resolve_value(self.wrapped, 'self_attn.out_proj.scales'),
            _resolve_value(self.wrapped, 'self_attn.out_proj.biases'),
            _resolve_value(self.wrapped, 'ffn_norm.weight'),
            _resolve_value(self.wrapped, 'feed_forward.w1.weight'),
            _resolve_value(self.wrapped, 'feed_forward.w1.scales'),
            _resolve_value(self.wrapped, 'feed_forward.w1.biases'),
            _resolve_value(self.wrapped, 'feed_forward.w3.weight'),
            _resolve_value(self.wrapped, 'feed_forward.w3.scales'),
            _resolve_value(self.wrapped, 'feed_forward.w3.biases'),
            _resolve_value(self.wrapped, 'feed_forward.w2.weight'),
            _resolve_value(self.wrapped, 'feed_forward.w2.scales'),
            _resolve_value(self.wrapped, 'feed_forward.w2.biases'),
        ))

    def __call__(self, a0, a1, cache=None):
        _n = a0.shape[1] if isinstance(a0, mx.array) and a0.ndim > 1 else -1
        if not (2 <= _n <= 2048 and a0 is not None and a0.shape == (1, _n, 2048) and a0.dtype == mx.bfloat16 and a1 == 'causal' and getattr(cache, 'offset', None) == 0):
            return self.wrapped(a0, a1, cache=cache)
        _w = self._weights
        v0 = a0
        v1 = _w[0]
        v2 = mx.fast.rms_norm(v0, v1, 1e-05)
        v3 = _w[1]
        v4 = _w[2]
        v5 = _w[3]
        v6 = mx.quantized_matmul(v2, v3, scales=v4, biases=v5, transpose=True, group_size=64, bits=4, mode='affine')
        v7 = _w[4]
        v8 = _w[5]
        v9 = _w[6]
        v10 = mx.quantized_matmul(v2, v7, scales=v8, biases=v9, transpose=True, group_size=64, bits=4, mode='affine')
        v11 = _w[7]
        v12 = _w[8]
        v13 = _w[9]
        v14 = mx.quantized_matmul(v2, v11, scales=v12, biases=v13, transpose=True, group_size=64, bits=4, mode='affine')
        v15 = v6.reshape(1, _n, 32, -1)
        v16 = _w[10]
        v17 = mx.fast.rms_norm(v15, v16, 1e-05)
        v18 = v17.transpose(0, 2, 1, 3)
        v19 = v10.reshape(1, _n, 8, -1)
        v20 = _w[11]
        v21 = mx.fast.rms_norm(v19, v20, 1e-05)
        v22 = v21.transpose(0, 2, 1, 3)
        v23 = v14.reshape(1, _n, 8, -1)
        v24 = v23.transpose(0, 2, 1, 3)
        v25 = mx.fast.rope(v18, 64, traditional=False, base=1000000.0, scale=1.0, offset=0)
        v26 = mx.fast.rope(v22, 64, traditional=False, base=1000000.0, scale=1.0, offset=0)
        v27, v28 = flatten_arrays(cache.update_and_fetch(v26, v24))
        v29 = mx.fast.scaled_dot_product_attention(v25, v27, v28, scale=0.125, mask='causal', sinks=None)
        v30 = v29.transpose(0, 2, 1, 3)
        v31 = v30.reshape(1, _n, -1)
        v32 = _w[12]
        v33 = _w[13]
        v34 = _w[14]
        v35 = _w[15]
        _s = self._specs['r95aa6c37bb25ef99_prefill_bk64']
        _ins = [v31, v32, v33, v34, v0, v35]
        _outs = _kernels.try_sized(_s, _ins) if 439 <= _n <= 2048 else None
        if _outs is None:
            v36 = mx.quantized_matmul(v31, v32, scales=v33, biases=v34, transpose=True, group_size=64, bits=4, mode='affine')
            v37 = (v0 + v36)
            v38 = mx.fast.rms_norm(v37, v35, 1e-05)
        else:
            v37 = _outs[0]
            v38 = _outs[1]
        v39 = _w[16]
        v40 = _w[17]
        v41 = _w[18]
        v42 = _w[19]
        v43 = _w[20]
        v44 = _w[21]
        _s = self._specs['r1f9367e50750eb01_unroll_hoist']
        _ins = [v38, v39, v40, v41, v42, v43, v44]
        _outs = _kernels.try_sized(_s, _ins) if 948 <= _n <= 2048 else None
        if _outs is None:
            v45 = mx.quantized_matmul(v38, v39, scales=v40, biases=v41, transpose=True, group_size=64, bits=4, mode='affine')
            v46 = mx.quantized_matmul(v38, v42, scales=v43, biases=v44, transpose=True, group_size=64, bits=4, mode='affine')
        else:
            v45 = _outs[0]
            v46 = _outs[1]
        v47, = flatten_arrays(_kernels.imported('mlx_lm.models.activations.swiglu')(v45, v46))
        v48 = _w[22]
        v49 = _w[23]
        v50 = _w[24]
        _s = self._specs['r036a72bd97248ec8_s0tile_sgfullunroll']
        _ins = [v47, v48, v49, v50, v37]
        _outs = _kernels.try_sized(_s, _ins) if 948 <= _n <= 2048 else None
        if _outs is None:
            v51 = mx.quantized_matmul(v47, v48, scales=v49, biases=v50, transpose=True, group_size=64, bits=4, mode='affine')
            v52 = (v37 + v51)
        else:
            v52 = _outs[0]
        return v52


# serves model.model.layers.15
class W_rae66687cb9df03fe_predeq_sg2x4(ReplayWrapper):
    KERNEL_IDS = ['rae66687cb9df03fe_predeq_sg2x4']

    def __init__(self, wrapped, specs=None):
        super().__init__(wrapped, specs)
        object.__setattr__(self, '_weights', (
            _resolve_value(self.wrapped, 'operator_norm.weight'),
            _resolve_value(self.wrapped, 'conv.in_proj.weight'),
            _resolve_value(self.wrapped, 'conv.in_proj.scales'),
            _resolve_value(self.wrapped, 'conv.in_proj.biases'),
            _resolve_value(self.wrapped, 'conv.conv.weight'),
            _resolve_value(self.wrapped, 'conv.out_proj.weight'),
            _resolve_value(self.wrapped, 'conv.out_proj.scales'),
            _resolve_value(self.wrapped, 'conv.out_proj.biases'),
            _resolve_value(self.wrapped, 'ffn_norm.weight'),
            _resolve_value(self.wrapped, 'feed_forward.w1.weight'),
            _resolve_value(self.wrapped, 'feed_forward.w1.scales'),
            _resolve_value(self.wrapped, 'feed_forward.w1.biases'),
            _resolve_value(self.wrapped, 'feed_forward.w3.weight'),
            _resolve_value(self.wrapped, 'feed_forward.w3.scales'),
            _resolve_value(self.wrapped, 'feed_forward.w3.biases'),
            _resolve_value(self.wrapped, 'feed_forward.w2.weight'),
            _resolve_value(self.wrapped, 'feed_forward.w2.scales'),
            _resolve_value(self.wrapped, 'feed_forward.w2.biases'),
        ))

    def __call__(self, a0, a1, cache=None):
        _n = a0.shape[1] if isinstance(a0, mx.array) and a0.ndim > 1 else -1
        if not (2 <= _n <= 2048 and a0 is not None and a0.shape == (1, _n, 2048) and a0.dtype == mx.bfloat16 and a1 is None and _state_signature(cache) == ('ArraysCache', ('dict', (('cache', ('list', (None,))), ('left_padding', None), ('lengths', None))))):
            return self.wrapped(a0, a1, cache=cache)
        _w = self._weights
        v0 = a0
        v1 = _w[0]
        v2 = mx.fast.rms_norm(v0, v1, 1e-05)
        v3 = _w[1]
        v4 = _w[2]
        v5 = _w[3]
        _s = self._specs['rae66687cb9df03fe_predeq_sg2x4']
        _ins = [v2, v3, v4, v5]
        _outs = _kernels.try_sized(_s, _ins) if 948 <= _n <= 2048 else None
        if _outs is None:
            v6 = mx.quantized_matmul(v2, v3, scales=v4, biases=v5, transpose=True, group_size=64, bits=4, mode='affine')
            v7, v8, v9 = mx.split(v6, 3, axis=-1)
            v10 = (v7 * v9)
        else:
            v8 = _outs[0]
            v10 = _outs[1]
        cache.__getitem__(0)
        v11 = mx.zeros((1, 2, 2048), dtype=mx.bfloat16)
        v12 = mx.concatenate([v11, v10], axis=1)
        v13 = v12[(slice(None, None, None), slice(-2, None, None), slice(None, None, None))]
        cache.__setitem__(0, v13)
        v14 = _w[4]
        v15 = mx.conv1d(v12, v14, 1, 0, 1, 2048)
        v16 = (v8 * v15)
        v17 = _w[5]
        v18 = _w[6]
        v19 = _w[7]
        v20 = mx.quantized_matmul(v16, v17, scales=v18, biases=v19, transpose=True, group_size=64, bits=4, mode='affine')
        v21 = (v0 + v20)
        v22 = _w[8]
        v23 = mx.fast.rms_norm(v21, v22, 1e-05)
        v24 = _w[9]
        v25 = _w[10]
        v26 = _w[11]
        v27 = mx.quantized_matmul(v23, v24, scales=v25, biases=v26, transpose=True, group_size=64, bits=4, mode='affine')
        v28 = _w[12]
        v29 = _w[13]
        v30 = _w[14]
        v31 = mx.quantized_matmul(v23, v28, scales=v29, biases=v30, transpose=True, group_size=64, bits=4, mode='affine')
        v32, = flatten_arrays(_kernels.imported('mlx_lm.models.activations.swiglu')(v27, v31))
        v33 = _w[15]
        v34 = _w[16]
        v35 = _w[17]
        v36 = mx.quantized_matmul(v32, v33, scales=v34, biases=v35, transpose=True, group_size=64, bits=4, mode='affine')
        v37 = (v21 + v36)
        return v37
