"""Wrapper generation: readable Python whose __call__ replays the
scope's recorded op stream with shipped cuts replaced by kernel calls.

Generated source calls ops by live mx attribute lookup and operators, so
record-mode retraces see every replayed op; kernels go through
autotuner_runtime.kernels.call, which record mode also patches. Both dispatch
paths live in the generated code: the fallback path IS the original op
sequence, so shapes no kernel covers need no library magic.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import mlx.core as mx

from ..trace.recorder import ArrayRef, OPAQUE_OP, compiled_path, dtype_name
from ..trace.types import ScopeCall, Trace, TraceNode
from autotuner_runtime.kernels import KernelSpec


class NotReplayable(RuntimeError):
    """This scope cannot host a generated wrapper; the message names why."""


@dataclass(frozen=True)
class Splice:
    """One shipped region cut inside a scope: replace [start_seq..end_seq]
    with the kernel, inputs and outputs in the kernel's declared order."""

    kernel: KernelSpec
    start_seq: int
    end_seq: int
    input_ids: tuple[int, ...]
    output_ids: tuple[int, ...]
    fingerprint: str = ""


@dataclass
class EmittedWrapper:
    class_name: str
    scope_path: str        # tree path of the wrapped module ("" for the root)
    source: str            # the class definition
    span_map: list         # per emitted op: (op, baseline_address, baseline_position)
    kernel_ids: list[str]


MODULE_HEADER = '''\
"""Generated by autotuner bind. Replays recorded op streams with shipped cuts
replaced by kernel calls; do not edit."""

import mlx.core as mx
from autotuner_runtime import kernels as _kernels
from autotuner_runtime.swap import ReplayWrapper
'''

_DUNDER_FMT = {
    "__add__": "({0} + {1})", "__radd__": "({1} + {0})", "__iadd__": "({0} + {1})",
    "__sub__": "({0} - {1})", "__rsub__": "({1} - {0})", "__isub__": "({0} - {1})",
    "__mul__": "({0} * {1})", "__rmul__": "({1} * {0})", "__imul__": "({0} * {1})",
    "__truediv__": "({0} / {1})", "__rtruediv__": "({1} / {0})", "__itruediv__": "({0} / {1})",
    "__floordiv__": "({0} // {1})", "__rfloordiv__": "({1} // {0})",
    "__mod__": "({0} % {1})", "__rmod__": "({1} % {0})",
    "__pow__": "({0} ** {1})", "__rpow__": "({1} ** {0})",
    "__matmul__": "({0} @ {1})", "__imatmul__": "({0} @ {1})",
    "__and__": "({0} & {1})", "__or__": "({0} | {1})", "__xor__": "({0} ^ {1})",
    "__lshift__": "({0} << {1})", "__rshift__": "({0} >> {1})",
    "__neg__": "(-{0})", "__abs__": "abs({0})", "__invert__": "(~{0})",
    "__eq__": "({0} == {1})", "__ne__": "({0} != {1})",
    "__lt__": "({0} < {1})", "__le__": "({0} <= {1})",
    "__gt__": "({0} > {1})", "__ge__": "({0} >= {1})",
}


def scope_tree_path(address: str) -> str:
    """'layers.3@0' -> 'layers.3'; the root '@0' -> ''."""
    return address.rsplit("@", 1)[0]


def scope_nodes(trace: Trace, scope: ScopeCall) -> list[TraceNode]:
    depth = len(scope.stack)
    nodes = [n for n in trace.nodes if n.module_stack[:depth] == scope.stack]
    if nodes:
        seqs = [n.seq for n in nodes]
        if seqs != list(range(seqs[0], seqs[-1] + 1)):
            raise NotReplayable(
                f"scope {scope.address!r} ops are not contiguous in the record"
            )
    return nodes


def _literal(value: object) -> str:
    if isinstance(value, ArrayRef):
        raise NotReplayable("array reference where a literal was expected")
    if isinstance(value, mx.Dtype):
        return f"mx.{dtype_name(value)}"
    if isinstance(value, slice):
        return f"slice({_literal(value.start)}, {_literal(value.stop)}, {_literal(value.step)})"
    if isinstance(value, tuple):
        inner = ", ".join(_literal(v) for v in value)
        return f"({inner},)" if len(value) == 1 else f"({inner})"
    if isinstance(value, list):
        return "[" + ", ".join(_literal(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{" + ", ".join(f"{k!r}: {_literal(v)}" for k, v in value.items()) + "}"
    if value is Ellipsis:
        return "..."
    if isinstance(value, (int, float, bool, str)) or value is None:
        return repr(value)
    raise NotReplayable(f"cannot emit literal for {type(value).__name__}: {value!r}")


class _Emitter:
    def __init__(self, trace: Trace, scope: ScopeCall):
        self.trace = trace
        self.scope = scope
        self.lines: list[str] = []
        self.span_map: list = []
        self.bound: set[int] = set()

    def name(self, aid: int) -> str:
        return f"v{aid}"

    def value_expr(self, obj: object) -> str:
        """A template entry: ArrayRef -> variable, else literal, recursing into
        containers that may hold refs (getitem keys, op arg lists)."""
        if isinstance(obj, ArrayRef):
            return self._ref_name(obj)
        if isinstance(obj, tuple):
            inner = ", ".join(self.value_expr(v) for v in obj)
            return f"({inner},)" if len(obj) == 1 else f"({inner})"
        if isinstance(obj, list):
            return "[" + ", ".join(self.value_expr(v) for v in obj) + "]"
        if isinstance(obj, dict):
            return "{" + ", ".join(f"{k!r}: {self.value_expr(v)}" for k, v in obj.items()) + "}"
        if isinstance(obj, slice):
            return f"slice({self.value_expr(obj.start)}, {self.value_expr(obj.stop)}, {self.value_expr(obj.step)})"
        return _literal(obj)

    def _ref_name(self, ref: ArrayRef) -> str:
        aid = self._current_node.in_arrays[ref.index]
        return self.name(aid)

    def require(self, aid: int, node: TraceNode) -> None:
        if aid in self.bound:
            return
        if aid in self.trace.weights:
            self._bind_weight(aid)
            return
        raise NotReplayable(
            f"op {node.op!r} (seq {node.seq}) reads array {aid} which is neither a "
            f"scope argument, a weight under the scope, nor produced inside the scope"
        )

    def _bind_weight(self, aid: int) -> None:
        path = self.trace.weight_paths.get(aid)
        prefix = scope_tree_path(self.scope.address)
        if path is None:
            raise NotReplayable(f"weight {aid} has no recorded model path")
        if prefix:
            if not (path == prefix or path.startswith(prefix + ".")):
                raise NotReplayable(
                    f"weight at {path!r} lives outside the scope {prefix!r}; "
                    f"the wrapper can only reach weights through its wrapped module"
                )
            rel = path[len(prefix):].lstrip(".")
        else:
            rel = path
        accessor = "self.wrapped"
        for part in rel.split(".") if rel else []:
            if part.isidentifier():
                accessor += f".{part}"
            elif part.isdigit():
                accessor += f"[{part}]"
            else:
                accessor += f"[{part!r}]"
        self.lines.append(f"{self.name(aid)} = {accessor}")
        self.bound.add(aid)

    def emit_node(self, node: TraceNode) -> None:
        if node.op == OPAQUE_OP:
            raise NotReplayable(
                f"scope {self.scope.address!r} contains a compiled call the harness cannot name"
            )
        self._current_node = node
        for aid in node.in_arrays:
            self.require(aid, node)
        args_t = node.scalar_args["args"]
        kwargs_t = node.scalar_args["kwargs"]
        short = node.op.removeprefix("array.")

        if compiled_path(node.op):
            # the model's own compiled section, called as the model calls it
            pieces = [self.value_expr(a) for a in args_t]
            pieces += [f"{k}={self.value_expr(v)}" for k, v in kwargs_t.items()]
            self._assign(node, f"_kernels.imported({compiled_path(node.op)!r})({', '.join(pieces)})")
        elif node.op.startswith("mx."):
            pieces = [self.value_expr(a) for a in args_t]
            pieces += [f"{k}={self.value_expr(v)}" for k, v in kwargs_t.items()]
            expr = f"{node.op}({', '.join(pieces)})"
            self._assign(node, expr)
        elif short in _DUNDER_FMT:
            operands = [self.value_expr(a) for a in args_t]
            self._assign(node, _DUNDER_FMT[short].format(*operands))
        elif short == "__getitem__":
            base = self.value_expr(args_t[0])
            key = self.value_expr(args_t[1])
            self._assign(node, f"{base}[{key}]")
        elif short == "__setitem__":
            base = self.value_expr(args_t[0])
            key = self.value_expr(args_t[1])
            val = self.value_expr(args_t[2])
            self.lines.append(f"{base}[{key}] = {val}")
            new_id = node.out_arrays[0]
            self.lines.append(f"{self.name(new_id)} = {base}")
            self.bound.add(new_id)
            self.span_map.append((node.op, node.module_address, node.position_in_module))
            return
        elif short == "T":
            self._assign(node, f"{self.value_expr(args_t[0])}.T")
        elif node.op.startswith("array."):
            base = self.value_expr(args_t[0])
            pieces = [self.value_expr(a) for a in args_t[1:]]
            pieces += [f"{k}={self.value_expr(v)}" for k, v in kwargs_t.items()]
            self._assign(node, f"{base}.{short}({', '.join(pieces)})")
        else:
            raise NotReplayable(f"no emission rule for op {node.op!r}")

    def _assign(self, node: TraceNode, expr: str) -> None:
        outs = [self.name(a) for a in node.out_arrays]
        if len(outs) == 1:
            self.lines.append(f"{outs[0]} = {expr}")
        else:
            self.lines.append(f"{', '.join(outs)} = {expr}")
        self.bound.update(node.out_arrays)
        self.span_map.append((node.op, node.module_address, node.position_in_module))

    def emit_splice(self, splice: Splice, span: list[TraceNode]) -> None:
        for node in span:
            self._current_node = node
            for aid in node.in_arrays:
                if aid not in self.bound and aid not in {
                    o for n in span for o in n.out_arrays
                }:
                    self.require(aid, node)
        kid = splice.kernel.kernel_id
        ins = ", ".join(self.name(a) for a in splice.input_ids)
        self.lines.append(f"_s = self._specs[{kid!r}]")
        self.lines.append(f"_ins = [{ins}]")
        self.lines.append(f"if _kernels.fallback_fires(_s, _ins):")
        saved = self.lines
        self.lines = []
        for node in span:
            self.emit_node(node)
        fallback_lines = self.lines
        del self.span_map[-len(span):]  # the fallback path is not the primary stream
        self.lines = saved
        for line in fallback_lines:
            self.lines.append("    " + line)
        self.lines.append("else:")
        self.lines.append(f"    _outs = _kernels.call(_s, _ins)")
        for i, aid in enumerate(splice.output_ids):
            self.lines.append(f"    {self.name(aid)} = _outs[{i}]")
        self.bound.update(splice.output_ids)
        self.bound.update(o for n in span for o in n.out_arrays)
        self.span_map.append(("custom_kernel", splice.fingerprint, kid))


def emit_wrapper(
    trace: Trace,
    scope: ScopeCall,
    splices: list[Splice],
    class_name: str,
) -> EmittedWrapper:
    """One wrapper class for one scope. splices empty -> the identity form."""
    nodes = scope_nodes(trace, scope)
    if not nodes:
        raise NotReplayable(f"scope {scope.address!r} recorded no ops")
    em = _Emitter(trace, scope)

    # bind entering arrays from the call arguments
    sig_parts = []
    for i, entry in enumerate(scope.args_template):
        if isinstance(entry, ArrayRef):
            sig_parts.append(f"a{i}")
            em.lines.append(f"{em.name(scope.arg_ids[entry.index])} = a{i}")
            em.bound.add(scope.arg_ids[entry.index])
        else:
            sig_parts.append(f"a{i}={_literal(entry)}")
    for k, v in scope.kwargs_template.items():
        if isinstance(v, ArrayRef):
            sig_parts.append(f"{k}=None")
            em.lines.append(f"{em.name(scope.arg_ids[v.index])} = {k}")
            em.bound.add(scope.arg_ids[v.index])
        else:
            sig_parts.append(f"{k}={_literal(v)}")

    by_start = {s.start_seq: s for s in splices}
    i = 0
    while i < len(nodes):
        node = nodes[i]
        splice = by_start.get(node.seq)
        if splice is not None:
            span = [n for n in nodes if splice.start_seq <= n.seq <= splice.end_seq]
            em.emit_splice(splice, span)
            i += len(span)
        else:
            em.emit_node(node)
            i += 1

    # the return expression follows the recorded output template
    def ret_expr(obj: object) -> str:
        if isinstance(obj, ArrayRef):
            aid = scope.out_ids[obj.index]
            if aid not in em.bound:
                raise NotReplayable(
                    f"scope returns array {aid} which the replay never produced"
                )
            return em.name(aid)
        if isinstance(obj, tuple):
            inner = ", ".join(ret_expr(v) for v in obj)
            return f"({inner},)" if len(obj) == 1 else f"({inner})"
        if isinstance(obj, list):
            return "[" + ", ".join(ret_expr(v) for v in obj) + "]"
        if isinstance(obj, dict):
            return "{" + ", ".join(f"{k!r}: {ret_expr(v)}" for k, v in obj.items()) + "}"
        return _literal(obj)

    ret = ret_expr(scope.out_template)

    body = "\n        ".join(em.lines) if em.lines else "pass"
    scope_path = scope_tree_path(scope.address)
    source = f'''

class {class_name}(ReplayWrapper):
    SCOPE = {scope_path!r}
    SPAN_MAP = {em.span_map!r}
    KERNEL_IDS = {[s.kernel.kernel_id for s in splices]!r}

    def __call__(self, {", ".join(sig_parts) if sig_parts else ""}):
        {body}
        return {ret}
'''
    return EmittedWrapper(
        class_name=class_name,
        scope_path=scope_path,
        source=source,
        span_map=em.span_map,
        kernel_ids=[s.kernel.kernel_id for s in splices],
    )
