"""Wrapper generation: readable Python whose __call__ replays the
scope's recorded op stream with shipped cuts replaced by kernel calls.

Generated source calls ops by live mx attribute lookup and operators, so
record-mode retraces see every replayed op; kernels go through
autotuner_runtime.kernels.call, which record mode also patches. Both dispatch
paths live in the generated code: the fallback path IS the original op
sequence, so shapes no kernel covers need no library magic.

A replay is exact only for the shapes it was recorded at: reshape targets,
slice bounds, and split sizes are literals from the trace. So every wrapper
first compares the entering arrays' shapes with the recorded ones and hands
any other call to the wrapped module unchanged.
"""

from __future__ import annotations

import ast
from dataclasses import dataclass, field
from typing import Mapping

import mlx.core as mx

from ..trace.recorder import (ArrayRef, OPAQUE_OP, UNNAMED_KERNEL_OP, ObjectRef, compiled_path,
                              dtype_name, kernel_path, state_method)
from ..trace.types import ScopeCall, Trace, TraceNode
from autotuner_runtime.kernels import KernelSpec


class NotReplayable(RuntimeError):
    """This scope cannot host a generated wrapper; the message names why."""


@dataclass(frozen=True)
class Splice:
    """One shipped region cut inside a scope: replace [start_seq..end_seq]
    with the kernel, inputs and outputs in the kernel's declared order."""

    kernel: KernelSpec
    start_seq: int
    end_seq: int
    input_ids: tuple[int, ...]
    output_ids: tuple[int, ...]
    fingerprint: str = ""


@dataclass
class EmittedWrapper:
    class_name: str
    scope_path: str        # tree path of the wrapped module ("" for the root)
    source: str            # the class definition
    span_map: list         # per emitted op: (op, baseline_address, baseline_position)
    kernel_ids: list[str]


MODULE_HEADER = '''\
"""Generated by autotuner bind. Replays recorded op streams with shipped cuts
replaced by kernel calls; do not edit."""

import mlx.core as mx
from autotuner_runtime import kernels as _kernels
from autotuner_runtime.captured_kernels import captured as _captured
from autotuner_runtime.swap import ReplayWrapper, flatten_arrays, resolve_value as _resolve_value
from autotuner_runtime.swap import state_signature as _state_signature
'''

_DUNDER_FMT = {
    "__add__": "({0} + {1})", "__radd__": "({1} + {0})",
    "__sub__": "({0} - {1})", "__rsub__": "({1} - {0})",
    "__mul__": "({0} * {1})", "__rmul__": "({1} * {0})",
    "__truediv__": "({0} / {1})", "__rtruediv__": "({1} / {0})",
    "__floordiv__": "({0} // {1})", "__rfloordiv__": "({1} // {0})",
    "__mod__": "({0} % {1})", "__rmod__": "({1} % {0})",
    "__pow__": "({0} ** {1})", "__rpow__": "({1} ** {0})",
    "__matmul__": "({0} @ {1})",
    "__and__": "({0} & {1})", "__or__": "({0} | {1})", "__xor__": "({0} ^ {1})",
    "__lshift__": "({0} << {1})", "__rshift__": "({0} >> {1})",
    "__neg__": "(-{0})", "__abs__": "abs({0})", "__invert__": "(~{0})",
    "__eq__": "({0} == {1})", "__ne__": "({0} != {1})",
    "__lt__": "({0} < {1})", "__le__": "({0} <= {1})",
    "__gt__": "({0} > {1})", "__ge__": "({0} >= {1})",
}


def scope_tree_path(address: str) -> str:
    """'layers.3@0' -> 'layers.3'; the root '@0' -> ''."""
    return address.rsplit("@", 1)[0]


def compose_scope_variants(
    traces: Mapping[str, Trace],
    installed: Mapping[str, Mapping[tuple[str, str], list[Splice]]],
    additions: Mapping[str, list[tuple[str, ScopeCall, Splice]]],
) -> dict[str, dict[tuple[str, str], list[Splice]]]:
    """Plan disjoint wrappers that retain every previously installed cut.

    A parent replay bypasses its children's Python calls. Move their cuts
    into that replay before replacing them, and route new child cuts into an
    already installed parent. All remapping uses the enclosing *call* in the
    original trace, so repeated calls and different workloads keep their own
    array identities. This function changes neither the model nor its records.
    """
    def beneath(path, root):
        return path == root or path.startswith(root + ".")

    paths = set(installed) | set(additions)
    roots = [path for path in sorted(paths)
             if not any(other != path and beneath(path, other) for other in paths)]
    scope_lookup = {name: {sc.address: sc for sc in trace.scope_calls}
                    for name, trace in traces.items()}
    updates = {}
    for root in roots:
        if not any(beneath(path, root) for path in additions):
            continue
        variants = {}

        def merge(workload, scope, splice, *, replace):
            address = next((address for address in scope.stack
                            if scope_tree_path(address) == root), None)
            if address is None:
                raise NotReplayable(
                    f"scope {scope.address!r} has no enclosing call at {root!r}")
            key = (workload, address)
            cuts = variants.setdefault(key, [])
            span = (splice.start_seq, splice.end_seq)
            matching = [old for old in cuts if (old.start_seq, old.end_seq) == span]
            if matching and not replace and any(old != splice for old in matching):
                raise NotReplayable(f"conflicting installed cuts at {workload}:{span}")
            cuts[:] = [old for old in cuts if (old.start_seq, old.end_seq) != span]
            cuts.append(splice)

        for path, prior in installed.items():
            if beneath(path, root):
                for (workload, address), cuts in prior.items():
                    for splice in cuts:
                        merge(workload, scope_lookup[workload][address], splice, replace=False)
        for path, new in additions.items():
            if beneath(path, root):
                for workload, scope, splice in new:
                    merge(workload, scope, splice, replace=True)
        for (workload, address), cuts in variants.items():
            cuts.sort(key=lambda splice: splice.start_seq)
            _validate_splices(scope_nodes(traces[workload], scope_lookup[workload][address]),
                              cuts, address)
        updates[root] = variants
    return updates


def covers_scope(nodes: list[TraceNode], spans) -> bool:
    """True when the cuts are the scope's whole calculation: nothing is left
    for a wrapper to rebuild or compile around the kernel calls."""
    return bool(spans) and {n.seq for n in nodes} == {
        seq for start, end in spans for seq in range(start, end + 1)}


def _validate_splices(nodes: list[TraceNode], splices: list[Splice], address: str) -> None:
    """Never silently omit a cut outside the replay or hidden by another cut."""
    previous_end = -1
    for splice in sorted(splices, key=lambda cut: cut.start_seq):
        if (not nodes or splice.start_seq > splice.end_seq
                or splice.start_seq < nodes[0].seq or splice.end_seq > nodes[-1].seq):
            raise NotReplayable(
                f"cut {splice.start_seq}:{splice.end_seq} is outside scope {address!r}")
        if splice.start_seq <= previous_end:
            raise NotReplayable(f"overlapping cuts in scope {address!r}")
        previous_end = splice.end_seq


def scope_nodes(trace: Trace, scope: ScopeCall) -> list[TraceNode]:
    depth = len(scope.stack)
    nodes = [n for n in trace.nodes if n.module_stack[:depth] == scope.stack]
    if nodes:
        seqs = [n.seq for n in nodes]
        if seqs != list(range(seqs[0], seqs[-1] + 1)):
            raise NotReplayable(
                f"scope {scope.address!r} ops are not contiguous in the record"
            )
    return nodes


def _literal(value: object) -> str:
    if isinstance(value, ArrayRef):
        raise NotReplayable("array reference where a literal was expected")
    if isinstance(value, ObjectRef):
        raise NotReplayable("an object argument where a literal was expected")
    if isinstance(value, mx.Dtype):
        return f"mx.{dtype_name(value)}"
    if isinstance(value, slice):
        return f"slice({_literal(value.start)}, {_literal(value.stop)}, {_literal(value.step)})"
    if isinstance(value, tuple):
        inner = ", ".join(_literal(v) for v in value)
        return f"({inner},)" if len(value) == 1 else f"({inner})"
    if isinstance(value, list):
        return "[" + ", ".join(_literal(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{" + ", ".join(f"{k!r}: {_literal(v)}" for k, v in value.items()) + "}"
    if value is Ellipsis:
        return "..."
    if isinstance(value, (int, float, bool, str)) or value is None:
        return repr(value)
    raise NotReplayable(f"cannot emit literal for {type(value).__name__}: {value!r}")


class _Emitter:
    def __init__(self, trace: Trace, scope: ScopeCall):
        self.trace = trace
        self.scope = scope
        self.lines: list[str] = []
        self.span_map: list = []
        self.bound: set[int] = set()
        self.weights: list[str] = []  # accessors resolved once at install, read as _w[i]
        self.names: dict[int, str] = {}

    def name(self, aid: int) -> str:
        # numbered in order of first use, so every copy of a region emits the
        # same body and the artifact can ship one class for all of them
        name = self.names.get(aid)
        if name is None:
            name = self.names[aid] = f"v{len(self.names)}"
        return name

    def value_expr(self, obj: object) -> str:
        """A template entry: ArrayRef -> variable, else literal, recursing into
        containers that may hold refs (getitem keys, op arg lists)."""
        if isinstance(obj, ArrayRef):
            return self._ref_name(obj)
        if isinstance(obj, tuple):
            inner = ", ".join(self.value_expr(v) for v in obj)
            return f"({inner},)" if len(obj) == 1 else f"({inner})"
        if isinstance(obj, list):
            return "[" + ", ".join(self.value_expr(v) for v in obj) + "]"
        if isinstance(obj, dict):
            return "{" + ", ".join(f"{k!r}: {self.value_expr(v)}" for k, v in obj.items()) + "}"
        if isinstance(obj, slice):
            return f"slice({self.value_expr(obj.start)}, {self.value_expr(obj.stop)}, {self.value_expr(obj.step)})"
        return _literal(obj)

    def _ref_name(self, ref: ArrayRef) -> str:
        aid = self._current_node.in_arrays[ref.index]
        return self.name(aid)

    def require(self, aid: int, node: TraceNode) -> None:
        if aid in self.bound:
            return
        if aid in self.trace.weights:
            self._bind_weight(aid)
            return
        raise NotReplayable(
            f"op {node.op!r} (seq {node.seq}) reads array {aid} which is neither a "
            f"scope argument, a weight under the scope, nor produced inside the scope"
        )

    def _bind_weight(self, aid: int) -> None:
        path = self.trace.weight_paths.get(aid)
        if path is None:
            raise NotReplayable(f"weight {aid} has no recorded model path")
        # a weight never moves, so resolve its accessor once at install and read
        # it by index, rather than walk the module tree on every call
        accessor = self._through_wrapped(path, f"weight at {path!r}")
        if accessor not in self.weights:
            self.weights.append(accessor)
        self.lines.append(f"{self.name(aid)} = _w[{self.weights.index(accessor)}]")
        self.bound.add(aid)

    def _through_wrapped(self, path: str, what: str) -> str:
        """The accessor for a model path, reached through the wrapped module;
        the path must lie under the scope."""
        prefix = scope_tree_path(self.scope.address)
        if prefix:
            if not (path == prefix or path.startswith(prefix + ".")):
                raise NotReplayable(
                    f"{what} lives outside the scope {prefix!r}; "
                    f"the wrapper can only reach it through its wrapped module"
                )
            rel = path[len(prefix):].lstrip(".")
        else:
            rel = path
        return f"_resolve_value(self.wrapped, {rel!r})"

    def _receiver(self, node: TraceNode) -> str:
        """The expression that reaches a state call's object at call time: a
        scope argument, found by identity, else its path through the
        wrapped module."""
        ref = node.scalar_args.get("receiver") or {}
        for base, template in self.scope_args():
            for index, expr in _object_refs(template, base):
                if self.scope.obj_ids[index] == ref.get("id"):
                    return expr
        if ref.get("path") is None:
            raise NotReplayable(f"{node.op} (seq {node.seq}) acts on an object the wrapper cannot reach")
        return self._through_wrapped(ref["path"], f"the object {node.op} acts on")

    def scope_args(self) -> list[tuple[str, object]]:
        """(parameter name, template) for every argument the scope was called with."""
        args = [(f"a{i}", entry) for i, entry in enumerate(self.scope.args_template)]
        return args + list(self.scope.kwargs_template.items())

    def call_args(self, args_t: tuple, kwargs_t: Mapping) -> str:
        pieces = [self.value_expr(a) for a in args_t]
        pieces += [f"{k}={self.value_expr(v)}" for k, v in kwargs_t.items()]
        return ", ".join(pieces)

    def emit_node(self, node: TraceNode) -> None:
        if node.op == OPAQUE_OP:
            raise NotReplayable(
                f"scope {self.scope.address!r} contains a compiled call the harness cannot name"
            )
        if node.op == UNNAMED_KERNEL_OP and node.kernel_definition is None:
            raise NotReplayable(
                f"scope {self.scope.address!r} contains a custom kernel the harness cannot name"
            )
        self._current_node = node
        for aid in node.in_arrays:
            self.require(aid, node)
        args_t = node.scalar_args["args"]
        kwargs_t = node.scalar_args["kwargs"]
        short = node.op.removeprefix("array.")

        if state_method(node.op):
            # the model's own state object, called as the model calls it
            call = f"{self._receiver(node)}.{state_method(node.op)}({self.call_args(args_t, kwargs_t)})"
            self._assign(node, call, structured=True)
        elif node.kernel_definition is not None:
            from autotuner_runtime.captured_kernels import definition_key
            key = definition_key(node.kernel_definition)
            call = f"_captured({key!r})({self.call_args(args_t, kwargs_t)})"
            self._assign(node, call, structured=True)
        elif compiled_path(node.op) or kernel_path(node.op):
            # the model's own compiled section or custom kernel, called as the model calls it
            path = compiled_path(node.op) or kernel_path(node.op)
            call = f"_kernels.imported({path!r})({self.call_args(args_t, kwargs_t)})"
            self._assign(node, call, structured=True)
        elif node.op.startswith("mx."):
            self._assign(node, f"{node.op}({self.call_args(args_t, kwargs_t)})")
        elif short in _DUNDER_FMT:
            operands = [self.value_expr(a) for a in args_t]
            self._assign(node, _DUNDER_FMT[short].format(*operands))
        elif short == "__getitem__":
            base = self.value_expr(args_t[0])
            key = self.value_expr(args_t[1])
            self._assign(node, f"{base}[{key}]")
        elif short == "__setitem__":
            base = self.value_expr(args_t[0])
            key = self.value_expr(args_t[1])
            val = self.value_expr(args_t[2])
            self.lines.append(f"{base}[{key}] = {val}")
            new_id = node.out_arrays[0]
            self.lines.append(f"{self.name(new_id)} = {base}")
            self.bound.add(new_id)
            self.span_map.append((node.op, node.module_address, node.position_in_module))
            return
        elif short == "T":
            self._assign(node, f"{self.value_expr(args_t[0])}.T")
        elif node.op.startswith("array."):
            base = self.value_expr(args_t[0])
            self._assign(node, f"{base}.{short}({self.call_args(args_t[1:], kwargs_t)})")
        else:
            raise NotReplayable(f"no emission rule for op {node.op!r}")

    def _assign(self, node: TraceNode, expr: str, structured: bool = False) -> None:
        """Bind the node's outputs to expr. A structured call (the model's
        own method or compiled section) returns whatever shape its code
        returns, so its arrays are taken in the recorder's flattening order."""
        outs = [self.name(a) for a in node.out_arrays]
        if not outs:
            self.lines.append(expr)
        elif structured:
            targets = ", ".join(outs) + ("," if len(outs) == 1 else "")
            self.lines.append(f"{targets} = flatten_arrays({expr})")
        else:
            self.lines.append(f"{', '.join(outs)} = {expr}")
        self.bound.update(node.out_arrays)
        self.span_map.append((node.op, node.module_address, node.position_in_module))

    def emit_splice(self, splice: Splice, span: list[TraceNode]) -> None:
        for node in span:
            self._current_node = node
            for aid in node.in_arrays:
                if aid not in self.bound and aid not in {
                    o for n in span for o in n.out_arrays
                }:
                    self.require(aid, node)
        kid = splice.kernel.kernel_id
        ins = ", ".join(self.name(a) for a in splice.input_ids)
        self.lines.append(f"_s = self._specs[{kid!r}]")
        self.lines.append(f"_ins = [{ins}]")
        self.lines.append("_outs = _kernels.try_call(_s, _ins)")
        self.lines.append("if _outs is None:")
        saved = self.lines
        self.lines = []
        for node in span:
            self.emit_node(node)
        fallback_lines = self.lines
        del self.span_map[-len(span):]  # the fallback path is not the primary stream
        self.lines = saved
        for line in fallback_lines:
            self.lines.append("    " + line)
        self.lines.append("else:")
        for i, aid in enumerate(splice.output_ids):
            self.lines.append(f"    {self.name(aid)} = _outs[{i}]")
        self.bound.update(splice.output_ids)
        self.bound.update(o for n in span for o in n.out_arrays)
        self.span_map.append(("custom_kernel", splice.fingerprint, kid))


def _object_refs(template: object, base: str):
    """(obj_ids index, access expression) for every object inside a call
    argument template: a bare object, or one inside a list or dict."""
    if isinstance(template, ObjectRef):
        yield template.index, base
    elif isinstance(template, (list, tuple)):
        for i, v in enumerate(template):
            yield from _object_refs(v, f"{base}[{i}]")
    elif isinstance(template, dict):
        for k, v in template.items():
            yield from _object_refs(v, f"{base}[{k!r}]")


def _replay_guard(trace: Trace, scope: ScopeCall) -> list[str]:
    """Only replay the shapes, dtypes, and scalar choices that were recorded."""
    checks = _variant_checks(trace, scope)
    if not checks:
        return []
    positional = [f"a{i}" for i in range(len(scope.args_template))]
    keywords = [f"{k}={k}" for k in scope.kwargs_template]
    return [f"if not ({' and '.join(checks)}):",
            f"    return self.wrapped({', '.join(positional + keywords)})"]


def _emit_replay(
    trace: Trace,
    scope: ScopeCall,
    splices: list[Splice],
) -> tuple[_Emitter, list[str], str]:
    """Build one replay body; callers decide how to guard and route it."""
    nodes = scope_nodes(trace, scope)
    if not nodes:
        raise NotReplayable(f"scope {scope.address!r} recorded no ops")
    _validate_splices(nodes, splices, scope.address)
    em = _Emitter(trace, scope)

    # positional arguments arrive as the model passed them, so they take no
    # defaults; keyword arguments default to the recorded literal, or None
    # for an array or an object (a cache) the body reaches by name
    sig_parts = []
    for i, entry in enumerate(scope.args_template):
        sig_parts.append(f"a{i}")
        if isinstance(entry, ArrayRef):
            em.lines.append(f"{em.name(scope.arg_ids[entry.index])} = a{i}")
            em.bound.add(scope.arg_ids[entry.index])
    for k, v in scope.kwargs_template.items():
        if isinstance(v, ArrayRef):
            sig_parts.append(f"{k}=None")
            em.lines.append(f"{em.name(scope.arg_ids[v.index])} = {k}")
            em.bound.add(scope.arg_ids[v.index])
        elif any(_object_refs(v, k)):
            sig_parts.append(f"{k}=None")
        else:
            sig_parts.append(f"{k}={_literal(v)}")

    by_start = {s.start_seq: s for s in splices}
    i = 0
    while i < len(nodes):
        node = nodes[i]
        splice = by_start.get(node.seq)
        if splice is not None:
            span = [n for n in nodes if splice.start_seq <= n.seq <= splice.end_seq]
            em.emit_splice(splice, span)
            i += len(span)
        else:
            em.emit_node(node)
            i += 1

    # the return expression follows the recorded output template
    def ret_expr(obj: object) -> str:
        if isinstance(obj, ArrayRef):
            aid = scope.out_ids[obj.index]
            if aid not in em.bound:
                raise NotReplayable(
                    f"scope returns array {aid} which the replay never produced"
                )
            return em.name(aid)
        if isinstance(obj, tuple):
            inner = ", ".join(ret_expr(v) for v in obj)
            return f"({inner},)" if len(obj) == 1 else f"({inner})"
        if isinstance(obj, list):
            return "[" + ", ".join(ret_expr(v) for v in obj) + "]"
        if isinstance(obj, dict):
            return "{" + ", ".join(f"{k!r}: {ret_expr(v)}" for k, v in obj.items()) + "}"
        return _literal(obj)

    ret = ret_expr(scope.out_template)
    return em, sig_parts, ret


def emit_wrapper(
    trace: Trace,
    scope: ScopeCall,
    splices: list[Splice],
    class_name: str,
) -> EmittedWrapper:
    """One wrapper class for one scope. splices empty -> the identity form."""
    em, sig_parts, ret = _emit_replay(trace, scope, splices)
    guard = _replay_guard(trace, scope)
    em.lines = guard + em.lines

    # weights are resolved once in __init__ and read by index in __call__, so
    # the model tree is walked at install, not per token. object.__setattr__
    # keeps the tuple out of the parameter tree; the model's weights must not be
    # replaced after install, which the harness and apply() never do.
    init = ""
    if em.weights:
        em.lines.insert(len(guard), "_w = self._weights")
        resolved = ",\n            ".join(em.weights)
        init = (
            "    def __init__(self, wrapped, specs=None):\n"
            "        super().__init__(wrapped, specs)\n"
            "        object.__setattr__(self, '_weights', (\n"
            f"            {resolved},\n"
            "        ))\n\n"
        )

    body = "\n        ".join(em.lines) if em.lines else "pass"
    scope_path = scope_tree_path(scope.address)
    source = f'''

class {class_name}(ReplayWrapper):
    KERNEL_IDS = {[s.kernel.kernel_id for s in splices]!r}

{init}    def __call__(self, {", ".join(sig_parts) if sig_parts else ""}):
        {body}
        return {ret}
'''
    return EmittedWrapper(
        class_name=class_name,
        scope_path=scope_path,
        source=source,
        span_map=em.span_map,
        kernel_ids=[s.kernel.kernel_id for s in splices],
    )


def _variant_checks(trace: Trace, scope: ScopeCall) -> tuple[str, ...]:
    """A recorded replay is valid for these entering shapes, dtypes, and
    scalar arguments, including a cache position when state calls occur."""
    nodes = scope_nodes(trace, scope)
    specs = trace.span_specs(nodes[0].seq, nodes[-1].seq)
    checks = []
    arguments = [(f"a{i}", entry) for i, entry in enumerate(scope.args_template)]
    arguments += sorted(scope.kwargs_template.items())
    for name, entry in arguments:
        if isinstance(entry, ArrayRef):
            aid = scope.arg_ids[entry.index]
            if aid not in specs:
                raise NotReplayable(f"scope argument {name} has no recorded shape or dtype")
            shape, dtype = specs[aid]
            checks.extend([f"{name} is not None", f"{name}.shape == {_literal(tuple(shape))}",
                           f"{name}.dtype == mx.{dtype}"])
        elif entry is None:
            checks.append(f"{name} is None")  # == would ask an array to compare itself with None
        elif not any(_object_refs(entry, name)):
            checks.append(f"{name} == {_literal(entry)}")
    # Python scalar reads are recorded as literals, with no provenance. A
    # matching number does not prove it came from cache.offset. Keep those
    # literals and restrict stateful replay to its recorded entry position.
    # Stateless child scopes need no position guard and remain reusable.
    em = _Emitter(trace, scope)
    seen = set()
    for node in nodes:
        if not state_method(node.op):
            continue
        receiver = node.scalar_args.get("receiver") or {}
        identity = receiver.get("id")
        if identity in seen:
            continue  # later updates describe a position inside this call
        seen.add(identity)
        offset = receiver.get("offset_before")
        if isinstance(offset, int) and not isinstance(offset, bool):
            expr = em._receiver(node)
            checks.append(f"getattr({expr}, 'offset', None) == {offset!r}")
        elif receiver.get("state_signature") is not None:
            expr = em._receiver(node)
            checks.append(f"_state_signature({expr}) == {_literal(receiver['state_signature'])}")
    return tuple(checks)


def _replay_identity(em: _Emitter, ret: str) -> tuple:
    """Ignore trace-local variable numbers when comparing duplicate routes.
    Rename Python names through the AST so string literals remain untouched."""
    names = {}

    class Rename(ast.NodeTransformer):
        def visit_Name(self, node):
            if node.id.startswith("v") and node.id[1:].isdigit():
                node.id = names.setdefault(node.id, f"v{len(names)}")
            return node

    tree = ast.parse("\n".join(em.lines + [f"return {ret}"]))
    return tuple(em.weights), ast.dump(Rename().visit(tree))


def emit_wrapper_variants(
    variants: list[tuple[Trace, ScopeCall, list[Splice]]],
    class_name: str,
) -> EmittedWrapper:
    """One generated class serving every recorded shape at a module path.

    Each (trace, scope, splices) describes one call variant; sequence and array
    ids belong only to that trace. The generated __call__ selects an inline
    replay with shape/dtype tests, then returns. Unrecorded calls go straight
    to the original module. A single variant keeps emit_wrapper's fast path.
    """
    if not variants:
        raise NotReplayable("a wrapper needs at least one recorded call variant")
    if len(variants) == 1:
        return emit_wrapper(*variants[0], class_name)

    path = scope_tree_path(variants[0][1].address)
    signature = None
    routes = {}
    bodies = []
    initializers = []
    span_maps = []
    kernel_ids = []
    for trace, scope, splices in variants:
        if scope_tree_path(scope.address) != path:
            raise NotReplayable("wrapper variants must belong to the same module path")
        em, sig_parts, ret = _emit_replay(trace, scope, splices)
        # Keep the original positional signature, allowing keyword insertion
        # order to differ between recordings but not their names or defaults.
        current = (len(scope.args_template), tuple(sorted(sig_parts)))
        if signature is not None and current != signature:
            raise NotReplayable("wrapper variants have incompatible argument signatures")
        signature = current
        checks = _variant_checks(trace, scope)
        identity = _replay_identity(em, ret)
        if checks in routes:
            if routes[checks] != identity:
                raise NotReplayable(
                    "the same argument shapes and dtypes select different recorded replays")
            continue
        routes[checks] = identity
        index = len(bodies)
        if em.weights:
            initializers.append(
                f"        object.__setattr__(self, '_weights_{index}', "
                f"({', '.join(em.weights)},))")
            em.lines.insert(0, f"_w = self._weights_{index}")
        condition = " and ".join(checks) or "True"
        lines = [f"        if {condition}:"]
        lines += ["            " + line for line in em.lines + [f"return {ret}"]]
        bodies.append("\n".join(lines))
        span_maps.append(em.span_map)
        kernel_ids.extend(s.kernel.kernel_id for s in splices
                          if s.kernel.kernel_id not in kernel_ids)

    # The first signature supplies defaults. Every other signature was checked
    # above, so passing an uncovered call through preserves its arguments.
    scope = variants[0][1]
    _, sig_parts, _ = _emit_replay(*variants[0])
    call_args = [f"a{i}" for i in range(len(scope.args_template))]
    call_args += [f"{k}={k}" for k in scope.kwargs_template]
    body = "\n".join(bodies + [f"        return self.wrapped({', '.join(call_args)})"])
    init = ""
    if initializers:
        init = ("    def __init__(self, wrapped, specs=None):\n"
                "        super().__init__(wrapped, specs)\n" + "\n".join(initializers) + "\n\n")
    # the scope path and span map travel in the swap table, not the class, so
    # one class can serve every module path with this exact body
    span_map = [entry for entries in span_maps for entry in entries]
    source = f'''

class {class_name}(ReplayWrapper):
    KERNEL_IDS = {kernel_ids!r}

{init}    def __call__(self, {", ".join(sig_parts)}):
{body}
'''
    return EmittedWrapper(class_name=class_name, scope_path=path, source=source,
                          span_map=span_map, kernel_ids=kernel_ids)
