const uint row = threadgroup_position_in_grid.x;
const uint lid = thread_position_in_threadgroup.x;
const uint sid = lid / 32u;
const uint lane = lid % 32u;
device const float4* src = (device const float4*)(in0 + row * 1024u);
device float4* dst = (device float4*)(out0 + row * 1024u);
float4 v = src[lid];
float s = (v.x + v.y) + (v.z + v.w);
s = metal::simd_sum(s);
threadgroup float red[8];
if (lane == 0u) red[sid] = s;
threadgroup_barrier(mem_flags::mem_threadgroup);
float tot = 0.0f;
for (uint i = 0; i < 8u; ++i) tot += red[i];
float mean = tot / 1024.0f;
float4 d = v - mean;
float ss = (d.x * d.x + d.y * d.y) + (d.z * d.z + d.w * d.w);
ss = metal::simd_sum(ss);
threadgroup_barrier(mem_flags::mem_threadgroup);
if (lane == 0u) red[sid] = ss;
threadgroup_barrier(mem_flags::mem_threadgroup);
float tot2 = 0.0f;
for (uint i = 0; i < 8u; ++i) tot2 += red[i];
float var = tot2 / 1024.0f;
float inv = metal::precise::rsqrt(var + 1e-05f);
dst[lid] = d * inv;
