const uint lid = thread_position_in_threadgroup.x;
const uint row = thread_position_in_grid.y;
const uint base = row * 1024u;
const device float4* p0 = (const device float4*)(in0 + base);
const device float4* p1 = (const device float4*)(in1 + base);
device float4* po = (device float4*)(out0 + base);
float4 x0 = p0[lid] + p1[lid];
float4 x1 = p0[lid + 128u] + p1[lid + 128u];
float m = nmax_(nmax_(nmax_(x0.x, x0.y), nmax_(x0.z, x0.w)), nmax_(nmax_(x1.x, x1.y), nmax_(x1.z, x1.w)));
for (uint o = 16u; o > 0u; o >>= 1) m = nmax_(m, simd_shuffle_xor(m, o));
threadgroup float sh[4];
const uint sg = lid >> 5;
const uint ln = lid & 31u;
if (ln == 0u) sh[sg] = m;
threadgroup_barrier(mem_flags::mem_threadgroup);
m = nmax_(nmax_(sh[0], sh[1]), nmax_(sh[2], sh[3]));
threadgroup_barrier(mem_flags::mem_threadgroup);
float4 e0, e1;
e0.x = metal::precise::exp(x0.x - m); e0.y = metal::precise::exp(x0.y - m); e0.z = metal::precise::exp(x0.z - m); e0.w = metal::precise::exp(x0.w - m);
e1.x = metal::precise::exp(x1.x - m); e1.y = metal::precise::exp(x1.y - m); e1.z = metal::precise::exp(x1.z - m); e1.w = metal::precise::exp(x1.w - m);
float s = (e0.x + e0.y) + (e0.z + e0.w) + (e1.x + e1.y) + (e1.z + e1.w);
for (uint o = 16u; o > 0u; o >>= 1) s += simd_shuffle_xor(s, o);
if (ln == 0u) sh[sg] = s;
threadgroup_barrier(mem_flags::mem_threadgroup);
s = (sh[0] + sh[1]) + (sh[2] + sh[3]);
po[lid] = e0 / s;
po[lid + 128u] = e1 / s;
