const uint lid = thread_position_in_threadgroup.x;
const uint row = thread_position_in_grid.y;
const uint base = row * 1024u;
const device float4* a4 = (const device float4*)(in0 + base);
const device float4* b4 = (const device float4*)(in1 + base);
float4 v = a4[lid] + b4[lid];
threadgroup float sh[8];
float s = (v.x + v.y) + (v.z + v.w);
s = metal::simd_sum(s);
if ((lid & 31u) == 0u) sh[lid >> 5] = s;
threadgroup_barrier(mem_flags::mem_threadgroup);
float tot = 0.0f;
for (uint i = 0; i < 8u; ++i) tot += sh[i];
const float mean = tot / 1024.0f;
threadgroup_barrier(mem_flags::mem_threadgroup);
float4 c = v - mean;
float sv = (c.x * c.x + c.y * c.y) + (c.z * c.z + c.w * c.w);
sv = metal::simd_sum(sv);
if ((lid & 31u) == 0u) sh[lid >> 5] = sv;
threadgroup_barrier(mem_flags::mem_threadgroup);
float var = 0.0f;
for (uint i = 0; i < 8u; ++i) var += sh[i];
const float scale = metal::precise::rsqrt(var / 1024.0f + 1e-05f);
const float4 g = ((const device float4*)in2)[lid];
const float4 bb = ((const device float4*)in3)[lid];
((device float4*)(out0 + base))[lid] = c * scale * g + bb;
